version: '3.8'

services:
  congratsemma:
    image: ghcr.io/xanox-org/congratsemma:latest
    container_name: congratsemma
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 40s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - web

networks:
  web:
    external: false